server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/setu_fyp?serverTimezone=GMT%2b8
    username: root
    password: zsj1364226740
  devtools:
    restart:
      additional-paths: src/main
      exclude: "static/**,public/**"
      polling-interval: 1000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fypspringbootcode.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印输出Mybatis的数据库日志 StdOutImpl是一个日志实现类
    map-underscore-to-camel-case: true  # 开启数据库字段下划线转驼峰 从数据库中取数据时精准对应到Bean的各个属性中


